# Generated by Django 5.2.5 on 2025-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
