# Generated by Django 5.2.5 on 2025-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
