# Generated by Django 5.2.5 on 2025-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_game_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
