# Generated by Django 5.2.5 on 2025-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_pick_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
