# Generated by Django 5.2.5 on 2025-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_alter_game_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
