# Generated by Django 5.2.5 on 2025-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_pick_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
