# Generated by Django 5.2.5 on 2025-09-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_pick_bonus_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_pick_window', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pool Settings',
                'verbose_name_plural': 'Pool Settings',
            },
        ),
    ]
