# Generated by Django 5.2.5 on 2025-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_poolsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('text', models.TextField()),
            ],
        ),
    ]
