# Generated by Django 5.2.5 on 2025-09-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_emails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
