# Generated by Django 5.2.5 on 2025-09-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_rename_emails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolsettings',
            name='site_maintenance',
            field=models.BooleanField(default=False, help_text='If enabled, only superusers can access the site. Others see a maintenance page.'),
        ),
    ]
