# Generated by Django 5.2.5 on 2025-09-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_poolsettings_site_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
