# Generated by Django 5.2.5 on 2025-09-05 02:01

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_weeklynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklynote',
            name='notes',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
