# Generated by Django 5.2.5 on 2025-09-05 02:16

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_alter_weeklynote_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='weeklynote',
            name='notes',
            field=models.TextField(),
        ),
    ]
