# Generated by Django 5.2.5 on 2025-09-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_alter_email_text_alter_weeklynote_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
