# Generated by Django 5.2.5 on 2025-09-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0014_alter_email_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='text',
            new_name='email_text',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='data',
            new_name='pool_data',
        ),
        migrations.AddField(
            model_name='email',
            name='email_response_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='email_response_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='email_response_total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='game_recap_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='game_recap_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='game_recap_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='game_recap_total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='total_combined_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='total_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='total_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='truncated_game_recap_results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
