# Generated by Django 5.2.5 on 2025-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0015_rename_text_email_email_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=10, null=True),
        ),
    ]
