# Generated by Django 5.2.5 on 2025-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0016_team_conference_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
