# Generated by Django 5.2.5 on 2025-10-02 12:28

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0017_game_is_tie_team_losses_team_ties_team_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='winning_percentage',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('wins__gt', 0), ('losses__gt', 0), ('ties__gt', 0), _connector='OR'), then=models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('wins'), '+', django.db.models.expressions.CombinedExpression(models.Value(0.5), '*', models.F('ties'))), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('wins'), '+', models.F('losses')), '+', models.F('ties'))), output_field=models.FloatField())), default=0.0, output_field=models.FloatField()), output_field=models.FloatField()),
        ),
    ]
