# Generated by Django 5.2.5 on 2025-10-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0018_team_winning_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='winning_percentage',
        ),
    ]
